### ISSUE TITLE
TypeError in Vite HTTP Example

### ISSUE THREAD

**Issue by ajcwebdev** [marko-js/examples#25]
## Reproduction

Download the [`vite-http`](https://github.com/marko-js/examples/tree/master/examples/vite-http) template.

```bash
npx @marko/create marko-app --template vite-http
cd marko-app
npm run dev
```

After opening `localhost:3000`, the terminal and browser display the following error:

```
TypeError: Cannot read property 'headers' of undefined
    at new Accepts (/Users/ajcwebdev/marko-app/node_modules/accepts/index.js:37:22)
    at Proxy.Accepts (/Users/ajcwebdev/marko-app/node_modules/accepts/index.js:34:12)
    at Module.send (/src/send.js:15:27)
    at handler (src/index.js:7:6)
    at file:///Users/ajcwebdev/marko-app/index.js:34:15
```

**Comment by ajcwebdev** [comment]
Figured it out, the issue is you need to have Node 16 installed, Node 14 will fail. Would be useful to mention the Node requirements somewhere in the README.
